[phases.setup]
nixPkgs = ["nodejs-22_x", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pnpm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
